addons:
  apt:
    packages:
      - gfortran
      - binutils
      - cmake

script:
  - gfortran --version
  - mkdir build
  - cd build
  - cmake ..
  - make -j$(nproc)
  - make install
  - cd ..
  - |
    for f in input/LesHouches.in.*;
      do ./bin/SPheno $f;
      sed -i '1,5d' SPheno.spc
      diff -q SPheno.spc output/SPheno.spc.${f/input\/LesHouches.in./}
    done
